// Generated by gencpp from file lslidar_msgs/LslidarScanUnified.msg
// DO NOT EDIT!


#ifndef LSLIDAR_MSGS_MESSAGE_LSLIDARSCANUNIFIED_H
#define LSLIDAR_MSGS_MESSAGE_LSLIDARSCANUNIFIED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lslidar_msgs/LslidarPacket.h>

namespace lslidar_msgs
{
template <class ContainerAllocator>
struct LslidarScanUnified_
{
  typedef LslidarScanUnified_<ContainerAllocator> Type;

  LslidarScanUnified_()
    : header()
    , packets()  {
    }
  LslidarScanUnified_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , packets(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::lslidar_msgs::LslidarPacket_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lslidar_msgs::LslidarPacket_<ContainerAllocator> >::other >  _packets_type;
  _packets_type packets;





  typedef boost::shared_ptr< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> const> ConstPtr;

}; // struct LslidarScanUnified_

typedef ::lslidar_msgs::LslidarScanUnified_<std::allocator<void> > LslidarScanUnified;

typedef boost::shared_ptr< ::lslidar_msgs::LslidarScanUnified > LslidarScanUnifiedPtr;
typedef boost::shared_ptr< ::lslidar_msgs::LslidarScanUnified const> LslidarScanUnifiedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator1> & lhs, const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.packets == rhs.packets;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator1> & lhs, const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e88461d84a8074809d7778b3a6770073";
  }

  static const char* value(const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe88461d84a807480ULL;
  static const uint64_t static_value2 = 0x9d7778b3a6770073ULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_msgs/LslidarScanUnified";
  }

  static const char* value(const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#lslidar  scan packets\n"
"\n"
"Header           header         #standard ros message header\n"
"\n"
"LslidarPacket[] packets        #vector of raw packets\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: lslidar_msgs/LslidarPacket\n"
"# Raw Leishen LIDAR packet.\n"
"\n"
"time stamp              # packet timestamp\n"
"uint8[1212] data        # packet contents\n"
"\n"
;
  }

  static const char* value(const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.packets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LslidarScanUnified_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_msgs::LslidarScanUnified_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "packets[]" << std::endl;
    for (size_t i = 0; i < v.packets.size(); ++i)
    {
      s << indent << "  packets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lslidar_msgs::LslidarPacket_<ContainerAllocator> >::stream(s, indent + "    ", v.packets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_MSGS_MESSAGE_LSLIDARSCANUNIFIED_H
