// Generated by gencpp from file lslidar_msgs/lslidar_control.msg
// DO NOT EDIT!


#ifndef LSLIDAR_MSGS_MESSAGE_LSLIDAR_CONTROL_H
#define LSLIDAR_MSGS_MESSAGE_LSLIDAR_CONTROL_H

#include <ros/service_traits.h>


#include <lslidar_msgs/lslidar_controlRequest.h>
#include <lslidar_msgs/lslidar_controlResponse.h>


namespace lslidar_msgs
{

struct lslidar_control
{

typedef lslidar_controlRequest Request;
typedef lslidar_controlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct lslidar_control
} // namespace lslidar_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lslidar_msgs::lslidar_control > {
  static const char* value()
  {
    return "0d2a2bc3bb3a258db25b2d8c05ffa5d1";
  }

  static const char* value(const ::lslidar_msgs::lslidar_control&) { return value(); }
};

template<>
struct DataType< ::lslidar_msgs::lslidar_control > {
  static const char* value()
  {
    return "lslidar_msgs/lslidar_control";
  }

  static const char* value(const ::lslidar_msgs::lslidar_control&) { return value(); }
};


// service_traits::MD5Sum< ::lslidar_msgs::lslidar_controlRequest> should match
// service_traits::MD5Sum< ::lslidar_msgs::lslidar_control >
template<>
struct MD5Sum< ::lslidar_msgs::lslidar_controlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_msgs::lslidar_control >::value();
  }
  static const char* value(const ::lslidar_msgs::lslidar_controlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_msgs::lslidar_controlRequest> should match
// service_traits::DataType< ::lslidar_msgs::lslidar_control >
template<>
struct DataType< ::lslidar_msgs::lslidar_controlRequest>
{
  static const char* value()
  {
    return DataType< ::lslidar_msgs::lslidar_control >::value();
  }
  static const char* value(const ::lslidar_msgs::lslidar_controlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lslidar_msgs::lslidar_controlResponse> should match
// service_traits::MD5Sum< ::lslidar_msgs::lslidar_control >
template<>
struct MD5Sum< ::lslidar_msgs::lslidar_controlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lslidar_msgs::lslidar_control >::value();
  }
  static const char* value(const ::lslidar_msgs::lslidar_controlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lslidar_msgs::lslidar_controlResponse> should match
// service_traits::DataType< ::lslidar_msgs::lslidar_control >
template<>
struct DataType< ::lslidar_msgs::lslidar_controlResponse>
{
  static const char* value()
  {
    return DataType< ::lslidar_msgs::lslidar_control >::value();
  }
  static const char* value(const ::lslidar_msgs::lslidar_controlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LSLIDAR_MSGS_MESSAGE_LSLIDAR_CONTROL_H
