// Generated by gencpp from file lslidar_msgs/lslidar_controlResponse.msg
// DO NOT EDIT!


#ifndef LSLIDAR_MSGS_MESSAGE_LSLIDAR_CONTROLRESPONSE_H
#define LSLIDAR_MSGS_MESSAGE_LSLIDAR_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lslidar_msgs
{
template <class ContainerAllocator>
struct lslidar_controlResponse_
{
  typedef lslidar_controlResponse_<ContainerAllocator> Type;

  lslidar_controlResponse_()
    : status(false)  {
    }
  lslidar_controlResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct lslidar_controlResponse_

typedef ::lslidar_msgs::lslidar_controlResponse_<std::allocator<void> > lslidar_controlResponse;

typedef boost::shared_ptr< ::lslidar_msgs::lslidar_controlResponse > lslidar_controlResponsePtr;
typedef boost::shared_ptr< ::lslidar_msgs::lslidar_controlResponse const> lslidar_controlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator1> & lhs, const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator1> & lhs, const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lslidar_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lslidar_msgs/lslidar_controlResponse";
  }

  static const char* value(const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
"\n"
;
  }

  static const char* value(const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lslidar_controlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lslidar_msgs::lslidar_controlResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LSLIDAR_MSGS_MESSAGE_LSLIDAR_CONTROLRESPONSE_H
