(cl:defpackage lslidar_msgs-msg
  (:use )
  (:export
   "<LSLIDARC16SWEEP>"
   "LSLIDARC16SWEEP"
   "<LSLIDARC32SWEEP>"
   "LSLIDARC32SWEEP"
   "<LSLIDARPACKET>"
   "LSLIDARPACKET"
   "<LSLIDARPOINT>"
   "LSLIDARPOINT"
   "<LSLIDARSCAN>"
   "LSLIDARSCAN"
   "<LSLIDARSCANUNIFIED>"
   "LSLIDARSCANUNIFIED"
  ))

